CREATE USER 'apc'@'localhost' IDENTIFIED BY 'apc';
CREATE USER 'apc' IDENTIFIED BY 'apc';
FLUSH PRIVILEGES;
GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, LOCK TABLES, UPDATE,  REFERENCES, INSERT, INDEX, DROP, DELETE, CREATE VIEW, CREATE TEMPORARY TABLES ON `apc`.* TO 'apc'@'localhost' WITH GRANT OPTION;
GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, LOCK TABLES, UPDATE,  REFERENCES, INSERT, INDEX, DROP, DELETE, CREATE VIEW, CREATE TEMPORARY TABLES ON `apc`.* TO 'apc'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;