-- MySQL Script generated by MySQL Workbench
-- 03/04/15 15:56:35
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema apc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `apc` ;
CREATE SCHEMA IF NOT EXISTS `apc` DEFAULT CHARACTER SET utf8 ;
USE `apc` ;

-- -----------------------------------------------------
-- Table `apc`.`ControllerDefinition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`ControllerDefinition` (
  `ControllerDefinitionID` INT(10) NOT NULL,
  `Users` INT(10) NOT NULL,
  `ControllerName` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ControllerDefinitionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`ScenarioDefinition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`ScenarioDefinition` (
  `ScenarioDefinitionID` INT(10) NOT NULL,
  `ScenarioName` VARCHAR(200) NOT NULL,
  `ScenarioPath` VARCHAR(2000) NULL,
  PRIMARY KEY (`ScenarioDefinitionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`ScenarioExecution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`ScenarioExecution` (
  `ScenarioExecutionID` BIGINT(32) NOT NULL,
  `ScenarioDefintionID` INT(10) NOT NULL,
  `SummaryOnly` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ScenarioExecutionID`),
  INDEX `scenario_executions_fk_idx` (`ScenarioDefintionID` ASC),
  CONSTRAINT `scenario_executions_fk`
    FOREIGN KEY (`ScenarioDefintionID`)
    REFERENCES `apc`.`ScenarioDefinition` (`ScenarioDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`FailureDefinition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`FailureDefinition` (
  `FailureDefinitionID` INT(10) NOT NULL,
  `Name` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`FailureDefinitionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`TestcaseDefinition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`TestcaseDefinition` (
  `TestcaseDefinitionID` INT(10) NOT NULL,
  `TestcaseName` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`TestcaseDefinitionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`GoalDefinition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`GoalDefinition` (
  `GoalDefinitionID` INT(10) NOT NULL,
  `GoalName` TEXT NOT NULL,
  PRIMARY KEY (`GoalDefinitionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`IterationPerExecution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`IterationPerExecution` (
  `IterationPerExecutionID` INT(10) NOT NULL,
  `ScenarioExecutionID` BIGINT(32) NOT NULL,
  `ControllerDefinitionID` INT(10) NOT NULL,
  `GoalDefinitionID` INT(10) NOT NULL,
  `Name` VARCHAR(200) NOT NULL,
  `Position` INT(10) NOT NULL,
  `Duration` INT(10) NOT NULL,
  `RampupDone` INT(10) NULL,
  `RampdownStarted` INT(10) NULL,
  `StartTime` BIGINT(32) NULL,
  `EndTime` BIGINT(32) NULL,
  PRIMARY KEY (`IterationPerExecutionID`),
  INDEX `executions_iterations_fk_idx` (`ScenarioExecutionID` ASC),
  INDEX `controllers_iterations_fk_idx` (`ControllerDefinitionID` ASC),
  INDEX `fk_Iterations_Goals1_idx` (`GoalDefinitionID` ASC),
  CONSTRAINT `controllers_iterations_fk`
    FOREIGN KEY (`ControllerDefinitionID`)
    REFERENCES `apc`.`ControllerDefinition` (`ControllerDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `executions_iterations_fk`
    FOREIGN KEY (`ScenarioExecutionID`)
    REFERENCES `apc`.`ScenarioExecution` (`ScenarioExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Iterations_Goals1`
    FOREIGN KEY (`GoalDefinitionID`)
    REFERENCES `apc`.`GoalDefinition` (`GoalDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`ServerDefinition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`ServerDefinition` (
  `ServerDefinitionID` INT(10) NOT NULL,
  `IP` CHAR(200) NOT NULL,
  `Name` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`ServerDefinitionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`LocationDefinition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`LocationDefinition` (
  `LocationDefinitionID` INT NOT NULL,
  `LocationName` VARCHAR(300) NULL,
  PRIMARY KEY (`LocationDefinitionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`TestNodePerExecution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`TestNodePerExecution` (
  `TestNodePerExecutionID` INT(10) NOT NULL AUTO_INCREMENT,
  `TestNodeDefinitionID` INT(10) NOT NULL,
  `ScenarioExecutionID` BIGINT(32) NOT NULL,
  `LocationDefinitionID` INT NOT NULL,
  `ErrLog` MEDIUMTEXT NOT NULL,
  `OutputLog` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`TestNodePerExecutionID`),
  INDEX `executions_testnodesperexecution_fk_idx` (`ScenarioExecutionID` ASC),
  INDEX `testnodes_testnodesperscenario_fk_idx` (`TestNodeDefinitionID` ASC),
  INDEX `fk_TestNodePerExecution_LocationDefinition1_idx` (`LocationDefinitionID` ASC),
  CONSTRAINT `testnodes_testnodesperscenario_fk`
    FOREIGN KEY (`TestNodeDefinitionID`)
    REFERENCES `apc`.`ServerDefinition` (`ServerDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `executions_testnodesperexecution_fk`
    FOREIGN KEY (`ScenarioExecutionID`)
    REFERENCES `apc`.`ScenarioExecution` (`ScenarioExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TestNodePerExecution_LocationDefinition1`
    FOREIGN KEY (`LocationDefinitionID`)
    REFERENCES `apc`.`LocationDefinition` (`LocationDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`TestcaseExecution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`TestcaseExecution` (
  `TestcaseExecutionID` INT(10) NOT NULL AUTO_INCREMENT,
  `ScenarioExecutionID` BIGINT(32) NOT NULL,
  `TestcaseDefinitionID` INT(10) NOT NULL,
  `IterationPerExecutionID` INT(10) NOT NULL,
  `TestNodePerExecutionID` INT(10) NOT NULL,
  `Offset` INT(10) NOT NULL,
  `Duration` INT(10) NOT NULL,
  `Success` TINYINT(1) NOT NULL,
  `Timestamp` BIGINT(32) NOT NULL,
  `Type` VARCHAR(1) NOT NULL,
  `DetailedUsecaseExecution` TINYINT(1) NOT NULL,
  PRIMARY KEY (`TestcaseExecutionID`),
  INDEX `fk_transactions_executions1_idx` (`ScenarioExecutionID` ASC),
  INDEX `Timestamp_UNIQUE` (`Timestamp` ASC),
  INDEX `fk_TestcaseExecution_TestcaseDefinition1_idx` (`TestcaseDefinitionID` ASC),
  INDEX `fk_TestcaseExecution_IterationPerExecution1_idx` (`IterationPerExecutionID` ASC),
  INDEX `fk_TestcaseExecution_TestNodePerExecution1_idx` (`TestNodePerExecutionID` ASC),
  CONSTRAINT `fk_transactions_executions1`
    FOREIGN KEY (`ScenarioExecutionID`)
    REFERENCES `apc`.`ScenarioExecution` (`ScenarioExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TestcaseExecution_TestcaseDefinition1`
    FOREIGN KEY (`TestcaseDefinitionID`)
    REFERENCES `apc`.`TestcaseDefinition` (`TestcaseDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TestcaseExecution_IterationPerExecution1`
    FOREIGN KEY (`IterationPerExecutionID`)
    REFERENCES `apc`.`IterationPerExecution` (`IterationPerExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TestcaseExecution_TestNodePerExecution1`
    FOREIGN KEY (`TestNodePerExecutionID`)
    REFERENCES `apc`.`TestNodePerExecution` (`TestNodePerExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`FailingTestcaseExecution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`FailingTestcaseExecution` (
  `TestcaseExecutionID` INT(10) NOT NULL,
  `FailureID` INT(10) NOT NULL,
  PRIMARY KEY (`TestcaseExecutionID`),
  INDEX `failures_failuretransactions_fk_idx` (`FailureID` ASC),
  CONSTRAINT `transactions_failuretransactions_fk`
    FOREIGN KEY (`TestcaseExecutionID`)
    REFERENCES `apc`.`TestcaseExecution` (`TestcaseExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `failures_failuretransactions_fk`
    FOREIGN KEY (`FailureID`)
    REFERENCES `apc`.`FailureDefinition` (`FailureDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`ServerMonitoring`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`ServerMonitoring` (
  `ServerMonitoringID` INT(10) NOT NULL AUTO_INCREMENT,
  `ServerDefinitionID` INT(10) NOT NULL,
  `IterationPerExecutionID` INT(10) NOT NULL,
  `Type` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ServerMonitoringID`),
  INDEX `nodes_monitoring_fk_idx` (`ServerDefinitionID` ASC),
  INDEX `iterations_monitoring_fk_idx` (`IterationPerExecutionID` ASC),
  CONSTRAINT `iterations_monitoring_fk`
    FOREIGN KEY (`IterationPerExecutionID`)
    REFERENCES `apc`.`IterationPerExecution` (`IterationPerExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `nodes_monitoring_fk`
    FOREIGN KEY (`ServerDefinitionID`)
    REFERENCES `apc`.`ServerDefinition` (`ServerDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`StepDefinition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`StepDefinition` (
  `StepDefinitionID` INT(10) NOT NULL,
  `TestcaseDefinitionID` INT(10) NOT NULL,
  `Name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`StepDefinitionID`),
  INDEX `usecases_stepdefinitions_fk_idx` (`TestcaseDefinitionID` ASC),
  CONSTRAINT `usecases_stepdefinitions_fk`
    FOREIGN KEY (`TestcaseDefinitionID`)
    REFERENCES `apc`.`TestcaseDefinition` (`TestcaseDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`StepPerTestcaseExecution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`StepPerTestcaseExecution` (
  `StepPerTestcaseExecutionID` INT(10) NOT NULL AUTO_INCREMENT,
  `TestcaseExecutionID` INT(10) NOT NULL,
  `StepDefinitionID` INT(10) NOT NULL,
  `PositionInTestcase` SMALLINT(10) NOT NULL,
  `Duration` INT(10) NOT NULL,
  PRIMARY KEY (`StepPerTestcaseExecutionID`),
  INDEX `steps_stepspertransaction_fk_idx` (`StepDefinitionID` ASC),
  INDEX `transactions_stepspertransaction_fk_idx` (`TestcaseExecutionID` ASC),
  CONSTRAINT `transactions_stepspertransaction_fk`
    FOREIGN KEY (`TestcaseExecutionID`)
    REFERENCES `apc`.`TestcaseExecution` (`TestcaseExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `steps_stepspertransaction_fk`
    FOREIGN KEY (`StepDefinitionID`)
    REFERENCES `apc`.`StepDefinition` (`StepDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`RequestDefinition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`RequestDefinition` (
  `RequestDefinitionID` INT NOT NULL,
  `MIME` VARCHAR(45) NOT NULL,
  `RequestValue` VARCHAR(600) NOT NULL,
  PRIMARY KEY (`RequestDefinitionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`RequestPerStep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`RequestPerStep` (
  `RequestPerStepID` INT(10) NOT NULL AUTO_INCREMENT,
  `StepPerTestcaseExecutionID` INT(10) NOT NULL,
  `RequestDefinitionID` INT NOT NULL,
  `Duration` INT(10) NOT NULL,
  `Response` BLOB NOT NULL,
  `RequestHeaders` VARCHAR(3000) NULL,
  `ResponseCode` INT(10) NULL,
  PRIMARY KEY (`RequestPerStepID`),
  INDEX `steps_responses_fk_idx` (`StepPerTestcaseExecutionID` ASC),
  INDEX `fk_Requests_RequestDefinition1_idx` (`RequestDefinitionID` ASC),
  CONSTRAINT `steps_responses_fk`
    FOREIGN KEY (`StepPerTestcaseExecutionID`)
    REFERENCES `apc`.`StepPerTestcaseExecution` (`StepPerTestcaseExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Requests_RequestDefinition1`
    FOREIGN KEY (`RequestDefinitionID`)
    REFERENCES `apc`.`RequestDefinition` (`RequestDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`SummaryData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`SummaryData` (
  `SummaryEntryID` INT NOT NULL AUTO_INCREMENT,
  `PercentileFound` TINYINT(1) NOT NULL,
  `TotalSuccess` INT(10) NOT NULL,
  `TotalFailures` INT(10) NOT NULL,
  `MaxDuration` INT(10) NULL,
  `MinDuration` INT(10) NULL,
  `AvgDuration` INT(10) NULL,
  `DurationStdDev` INT(10) NULL,
  `Duration85` INT(10) NULL,
  `Duration90` INT(10) NULL,
  `Duration95` INT(10) NULL,
  `MaxSize` INT(10) NULL,
  `MinSize` INT(10) NULL,
  `AvgSize` INT(10) NULL,
  `SizeStdDev` INT(10) NULL,
  `Size85` INT(10) NULL,
  `Size90` INT(10) NULL,
  `Size95` INT(10) NULL,
  `ScenarioExecutionID` BIGINT(32) NOT NULL,
  PRIMARY KEY (`SummaryEntryID`),
  UNIQUE INDEX `SummaryEntryID_UNIQUE` (`SummaryEntryID` ASC),
  INDEX `fk_SummaryData_ScenarioExecution1_idx` (`ScenarioExecutionID` ASC),
  CONSTRAINT `fk_SummaryData_ScenarioExecution1`
    FOREIGN KEY (`ScenarioExecutionID`)
    REFERENCES `apc`.`ScenarioExecution` (`ScenarioExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`TestcaseSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`TestcaseSummary` (
  `TestcaseSummaryID` INT(10) NOT NULL,
  `TestcaseDefinitionID` INT(10) NOT NULL,
  `TestcasePercentage` DOUBLE NOT NULL,
  `Users` INT(10) NOT NULL,
  `SummaryEntryID` INT NULL,
  PRIMARY KEY (`TestcaseSummaryID`),
  INDEX `usecases_sequence_fk_idx` (`TestcaseDefinitionID` ASC),
  INDEX `fk_TestcasePerIteration_SummaryData1_idx` (`SummaryEntryID` ASC),
  CONSTRAINT `usecases_sequence_fk`
    FOREIGN KEY (`TestcaseDefinitionID`)
    REFERENCES `apc`.`TestcaseDefinition` (`TestcaseDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TestcasePerIteration_SummaryData1`
    FOREIGN KEY (`SummaryEntryID`)
    REFERENCES `apc`.`SummaryData` (`SummaryEntryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`FailingStep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`FailingStep` (
  `StepPerTestcaseExecutionID` INT(10) NOT NULL,
  `FailureDefinitionID` INT(10) NOT NULL,
  PRIMARY KEY (`StepPerTestcaseExecutionID`),
  INDEX `fk_FailingStep_FailureDefinition1_idx` (`FailureDefinitionID` ASC),
  CONSTRAINT `stepspertransaction_warningsteps_fk`
    FOREIGN KEY (`StepPerTestcaseExecutionID`)
    REFERENCES `apc`.`StepPerTestcaseExecution` (`StepPerTestcaseExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FailingStep_FailureDefinition1`
    FOREIGN KEY (`FailureDefinitionID`)
    REFERENCES `apc`.`FailureDefinition` (`FailureDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`ResourceMonitoring`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`ResourceMonitoring` (
  `ResourceMonitoringID` INT(10) NOT NULL AUTO_INCREMENT,
  `EntryType` VARCHAR(200) NULL,
  `TestNodeMonitoringID` INT(10) NOT NULL,
  INDEX `fk_APCMonitoringEntries_Monitoring1_idx` (`TestNodeMonitoringID` ASC),
  PRIMARY KEY (`ResourceMonitoringID`),
  CONSTRAINT `fk_APCMonitoringEntries_Monitoring1`
    FOREIGN KEY (`TestNodeMonitoringID`)
    REFERENCES `apc`.`ServerMonitoring` (`ServerMonitoringID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`MonitoringData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`MonitoringData` (
  `MonitoringDataID` INT NOT NULL AUTO_INCREMENT,
  `ResourceMonitoringID` INT(10) NOT NULL,
  `Value` DOUBLE NOT NULL,
  `Offset` INT NULL,
  PRIMARY KEY (`MonitoringDataID`),
  INDEX `fk_APCMonitoringData_APCMonitoringEntries1_idx` (`ResourceMonitoringID` ASC),
  CONSTRAINT `fk_APCMonitoringData_APCMonitoringEntries1`
    FOREIGN KEY (`ResourceMonitoringID`)
    REFERENCES `apc`.`ResourceMonitoring` (`ResourceMonitoringID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`IterationSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`IterationSummary` (
  `SummaryReportID` INT NOT NULL AUTO_INCREMENT,
  `IterationID` INT(10) NOT NULL,
  `SummaryType` VARCHAR(45) NULL,
  PRIMARY KEY (`SummaryReportID`),
  INDEX `fk_SummyReports_Iterations1_idx` (`IterationID` ASC),
  CONSTRAINT `fk_SummyReports_Iterations1`
    FOREIGN KEY (`IterationID`)
    REFERENCES `apc`.`IterationPerExecution` (`IterationPerExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`IterationSummaryData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`IterationSummaryData` (
  `IterationSummaryEntriesId` INT NOT NULL AUTO_INCREMENT,
  `SummaryReportID` INT NOT NULL,
  `Offset` INT NULL,
  `Value` DOUBLE NULL,
  PRIMARY KEY (`IterationSummaryEntriesId`),
  INDEX `fk_IterationSummaryEntries_IterationSummary1_idx` (`SummaryReportID` ASC),
  CONSTRAINT `fk_IterationSummaryEntries_IterationSummary1`
    FOREIGN KEY (`SummaryReportID`)
    REFERENCES `apc`.`IterationSummary` (`SummaryReportID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`StepSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`StepSummary` (
  `StepSummaryID` INT(10) NOT NULL AUTO_INCREMENT,
  `StepDefinitionID` INT(10) NOT NULL,
  `TestcaseSummaryID` INT(10) NOT NULL,
  `SummaryEntryID` INT NOT NULL,
  PRIMARY KEY (`StepSummaryID`),
  INDEX `fk_TransactionsSummary_SummaryEntries1_idx` (`SummaryEntryID` ASC),
  INDEX `fk_StepsSummary_StepDefinitions1_idx` (`StepDefinitionID` ASC),
  INDEX `fk_StepSummary_TestcaseSummary1_idx` (`TestcaseSummaryID` ASC),
  CONSTRAINT `fk_TransactionsSummary_SummaryEntries10`
    FOREIGN KEY (`SummaryEntryID`)
    REFERENCES `apc`.`SummaryData` (`SummaryEntryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_StepsSummary_StepDefinitions1`
    FOREIGN KEY (`StepDefinitionID`)
    REFERENCES `apc`.`StepDefinition` (`StepDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_StepSummary_TestcaseSummary1`
    FOREIGN KEY (`TestcaseSummaryID`)
    REFERENCES `apc`.`TestcaseSummary` (`TestcaseSummaryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`RequestSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`RequestSummary` (
  `RequestSummaryID` INT(10) NOT NULL AUTO_INCREMENT,
  `RequestDefinitionID` INT NOT NULL,
  `StepSummaryID` INT(10) NULL,
  `IterationPerExecutionID` INT(10) NULL,
  `SummaryEntryID` INT NOT NULL,
  PRIMARY KEY (`RequestSummaryID`),
  INDEX `fk_TransactionsSummary_SummaryEntries1_idx` (`SummaryEntryID` ASC),
  INDEX `fk_RequestSummary_RequestDefinition1_idx` (`RequestDefinitionID` ASC),
  INDEX `fk_RequestSummary_StepsSummary1_idx` (`StepSummaryID` ASC),
  INDEX `fk_RequestSummary_IterationPerExecution1_idx` (`IterationPerExecutionID` ASC),
  CONSTRAINT `fk_TransactionsSummary_SummaryEntries100`
    FOREIGN KEY (`SummaryEntryID`)
    REFERENCES `apc`.`SummaryData` (`SummaryEntryID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RequestSummary_RequestDefinition1`
    FOREIGN KEY (`RequestDefinitionID`)
    REFERENCES `apc`.`RequestDefinition` (`RequestDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RequestSummary_StepsSummary1`
    FOREIGN KEY (`StepSummaryID`)
    REFERENCES `apc`.`StepSummary` (`StepSummaryID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RequestSummary_IterationPerExecution1`
    FOREIGN KEY (`IterationPerExecutionID`)
    REFERENCES `apc`.`IterationPerExecution` (`IterationPerExecutionID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`TestcaseExecutionLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`TestcaseExecutionLog` (
  `TestcaseExecutionID` INT(10) NOT NULL,
  `OuptutLog` TEXT NOT NULL,
  `ErrorLog` TEXT NOT NULL,
  PRIMARY KEY (`TestcaseExecutionID`),
  CONSTRAINT `fk_TransactionLogs_Transactions1`
    FOREIGN KEY (`TestcaseExecutionID`)
    REFERENCES `apc`.`TestcaseExecution` (`TestcaseExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`PercentileCache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`PercentileCache` (
  `PercentileCacheID` INT NOT NULL AUTO_INCREMENT,
  `ResourceId` INT(10) NOT NULL,
  `Value` INT(10) NOT NULL,
  `LocationDefinitionID` INT NOT NULL,
  `TestNodePerExecutionID` INT(10) NOT NULL,
  PRIMARY KEY (`PercentileCacheID`),
  INDEX `index2` USING HASH (`ResourceId` ASC),
  INDEX `fk_PercentileCache_LocationDefinition1_idx` USING HASH (`LocationDefinitionID` ASC),
  INDEX `fk_PercentileCache_TestNodePerExecution1_idx` USING HASH (`TestNodePerExecutionID` ASC),
  INDEX `index3` USING BTREE (`Value` DESC))
ENGINE = MEMORY;


-- -----------------------------------------------------
-- Table `apc`.`RequestFailureSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`RequestFailureSummary` (
  `RequestFailureSummaryID` INT NOT NULL AUTO_INCREMENT,
  `RequestSummaryID` INT(10) NOT NULL,
  `FailureDefinitionID` INT(10) NOT NULL,
  `Total` INT(10) NOT NULL,
  PRIMARY KEY (`RequestFailureSummaryID`),
  UNIQUE INDEX `RequestFailureSummaryId_UNIQUE` (`RequestFailureSummaryID` ASC),
  INDEX `fk_RequestFailureSummary_RequestSummary1_idx` (`RequestSummaryID` ASC),
  INDEX `fk_RequestFailureSummary_FailureDefinition1_idx` (`FailureDefinitionID` ASC),
  INDEX `fk_RequestFailureSummary_SummaryData_idx` (`Total` ASC),
  CONSTRAINT `fk_RequestFailureSummary_RequestSummary1`
    FOREIGN KEY (`RequestSummaryID`)
    REFERENCES `apc`.`RequestSummary` (`RequestSummaryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RequestFailureSummary_FailureDefinition1`
    FOREIGN KEY (`FailureDefinitionID`)
    REFERENCES `apc`.`FailureDefinition` (`FailureDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RequestFailureSummary_SummaryData`
    FOREIGN KEY (`Total`)
    REFERENCES `apc`.`SummaryData` (`SummaryEntryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`StepFailureSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`StepFailureSummary` (
  `StepFailureSummaryID` INT NOT NULL AUTO_INCREMENT,
  `StepSummaryID` INT(10) NOT NULL,
  `FailureDefinitionID` INT(10) NOT NULL,
  `Total` INT(10) NOT NULL,
  PRIMARY KEY (`StepFailureSummaryID`),
  INDEX `fk_StepFailureSummary_StepSummary1_idx` (`StepSummaryID` ASC),
  INDEX `fk_StepFailureSummary_FailureDefinition1_idx` (`FailureDefinitionID` ASC),
  INDEX `fk_StepFailureSummary_SummaryData_idx` (`Total` ASC),
  CONSTRAINT `fk_StepFailureSummary_StepSummary1`
    FOREIGN KEY (`StepSummaryID`)
    REFERENCES `apc`.`StepSummary` (`StepSummaryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_StepFailureSummary_FailureDefinition1`
    FOREIGN KEY (`FailureDefinitionID`)
    REFERENCES `apc`.`FailureDefinition` (`FailureDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TestcaseFailureSummary_SummaryData`
    FOREIGN KEY (`Total`)
    REFERENCES `apc`.`SummaryData` (`SummaryEntryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_StepFailureSummary`
    FOREIGN KEY (`Total`)
    REFERENCES `apc`.`SummaryData` (`SummaryEntryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RequestFailureSummary`
    FOREIGN KEY (`Total`)
    REFERENCES `apc`.`SummaryData` (`SummaryEntryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`TestcaseFailureSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`TestcaseFailureSummary` (
  `TestcaseFailureSummaryID` INT NOT NULL AUTO_INCREMENT,
  `TestcasePerIterationID` INT(10) NOT NULL,
  `FailureDefinitionID` INT(10) NOT NULL,
  `Total` INT NOT NULL,
  PRIMARY KEY (`TestcaseFailureSummaryID`),
  INDEX `fk_TestcaseFailureSummary_TestcasePerIterationSummary1_idx` (`TestcasePerIterationID` ASC),
  INDEX `fk_TestcaseFailureSummary_FailureDefinition1_idx` (`FailureDefinitionID` ASC),
  INDEX `fk_TestcaseFailureSummary_SummaryData1_idx` (`Total` ASC),
  CONSTRAINT `fk_TestcaseFailureSummary_TestcasePerIterationSummary1`
    FOREIGN KEY (`TestcasePerIterationID`)
    REFERENCES `apc`.`TestcaseSummary` (`TestcaseSummaryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TestcaseFailureSummary_FailureDefinition1`
    FOREIGN KEY (`FailureDefinitionID`)
    REFERENCES `apc`.`FailureDefinition` (`FailureDefinitionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TestcaseFailureSummary_SummaryData1`
    FOREIGN KEY (`Total`)
    REFERENCES `apc`.`SummaryData` (`SummaryEntryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`FailingRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`FailingRequest` (
  `RequestPerStepID` INT(10) NOT NULL,
  `FailureDefinitionID` INT(10) NOT NULL,
  INDEX `fk_FailingStep_FailureDefinition1_idx` (`FailureDefinitionID` ASC),
  PRIMARY KEY (`RequestPerStepID`),
  CONSTRAINT `fk_FailingStep_FailureDefinition10`
    FOREIGN KEY (`FailureDefinitionID`)
    REFERENCES `apc`.`FailureDefinition` (`FailureDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FailingRequest_RequestPerStep1`
    FOREIGN KEY (`RequestPerStepID`)
    REFERENCES `apc`.`RequestPerStep` (`RequestPerStepID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apc`.`LocationPerIterationSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`LocationPerIterationSummary` (
  `LocationPerIterationSummaryID` INT NOT NULL,
  `LocationDefinitionID` INT NOT NULL,
  `IterationPerExecutionID` INT(10) NOT NULL,
  `TestcasePerIterationID` INT(10) NOT NULL,
  INDEX `fk_LocationPerIterationSummary_LocationDefinition1_idx` (`LocationDefinitionID` ASC),
  INDEX `fk_LocationPerIterationSummary_IterationPerExecution1_idx` (`IterationPerExecutionID` ASC),
  INDEX `fk_LocationPerIterationSummary_TestcasePerIterationSummary1_idx` (`TestcasePerIterationID` ASC),
  PRIMARY KEY (`LocationPerIterationSummaryID`),
  CONSTRAINT `fk_LocationPerIterationSummary_LocationDefinition1`
    FOREIGN KEY (`LocationDefinitionID`)
    REFERENCES `apc`.`LocationDefinition` (`LocationDefinitionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LocationPerIterationSummary_IterationPerExecution1`
    FOREIGN KEY (`IterationPerExecutionID`)
    REFERENCES `apc`.`IterationPerExecution` (`IterationPerExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LocationPerIterationSummary_TestcasePerIterationSummary1`
    FOREIGN KEY (`TestcasePerIterationID`)
    REFERENCES `apc`.`TestcaseSummary` (`TestcaseSummaryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`TestNodePerIterationSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`TestNodePerIterationSummary` (
  `TestNodePerIterationSummaryID` INT UNSIGNED NOT NULL,
  `TestNodePerExecutionID` INT(10) NOT NULL,
  `TestcasePerIterationID` INT(10) NOT NULL,
  `IterationPerExecutionID` INT(10) NOT NULL,
  INDEX `fk_TestNodePerIterationSummary_TestNodePerExecution1_idx` (`TestNodePerExecutionID` ASC),
  INDEX `fk_TestNodePerIterationSummary_TestcasePerIterationSummary1_idx` (`TestcasePerIterationID` ASC),
  PRIMARY KEY (`TestNodePerIterationSummaryID`),
  INDEX `fk_TestNodePerIterationSummary_IterationPerExecution1_idx` (`IterationPerExecutionID` ASC),
  CONSTRAINT `fk_TestNodePerIterationSummary_TestNodePerExecution1`
    FOREIGN KEY (`TestNodePerExecutionID`)
    REFERENCES `apc`.`TestNodePerExecution` (`TestNodePerExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TestNodePerIterationSummary_TestcasePerIterationSummary1`
    FOREIGN KEY (`TestcasePerIterationID`)
    REFERENCES `apc`.`TestcaseSummary` (`TestcaseSummaryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TestNodePerIterationSummary_IterationPerExecution1`
    FOREIGN KEY (`IterationPerExecutionID`)
    REFERENCES `apc`.`IterationPerExecution` (`IterationPerExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`TestcasePerIterationSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`TestcasePerIterationSummary` (
  `TestcasePerIterationSummaryID` INT NOT NULL,
  `IterationPerExecutionID` INT(10) NOT NULL,
  `TestcaseSummaryID` INT(10) NOT NULL,
  PRIMARY KEY (`TestcasePerIterationSummaryID`),
  INDEX `fk_TestcasePerIterationSummary_IterationPerExecution1_idx` (`IterationPerExecutionID` ASC),
  INDEX `fk_TestcasePerIterationSummary_TestcaseSummary1_idx` (`TestcaseSummaryID` ASC),
  CONSTRAINT `fk_TestcasePerIterationSummary_IterationPerExecution1`
    FOREIGN KEY (`IterationPerExecutionID`)
    REFERENCES `apc`.`IterationPerExecution` (`IterationPerExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TestcasePerIterationSummary_TestcaseSummary1`
    FOREIGN KEY (`TestcaseSummaryID`)
    REFERENCES `apc`.`TestcaseSummary` (`TestcaseSummaryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`NodePerIterationSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`NodePerIterationSummary` (
  `NodePerIterationSummaryID` INT NOT NULL,
  `IterationPerExecutionID` INT(10) NOT NULL,
  `TestcasePerIterationID` INT(10) NOT NULL,
  `TestNodePerExecutionID` INT(10) NOT NULL,
  INDEX `fk_LocationPerIterationSummary_IterationPerExecution1_idx` (`IterationPerExecutionID` ASC),
  INDEX `fk_LocationPerIterationSummary_TestcasePerIterationSummary1_idx` (`TestcasePerIterationID` ASC),
  PRIMARY KEY (`NodePerIterationSummaryID`),
  INDEX `fk_NodePerIterationSummary_TestNodePerExecution1_idx` (`TestNodePerExecutionID` ASC),
  CONSTRAINT `fk_LocationPerIterationSummary_IterationPerExecution10`
    FOREIGN KEY (`IterationPerExecutionID`)
    REFERENCES `apc`.`IterationPerExecution` (`IterationPerExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LocationPerIterationSummary_TestcasePerIterationSummary10`
    FOREIGN KEY (`TestcasePerIterationID`)
    REFERENCES `apc`.`TestcaseSummary` (`TestcaseSummaryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_NodePerIterationSummary_TestNodePerExecution1`
    FOREIGN KEY (`TestNodePerExecutionID`)
    REFERENCES `apc`.`TestNodePerExecution` (`TestNodePerExecutionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`ResponseCodeDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`ResponseCodeDetail` (
  `ResponseCodeDetailId` INT NOT NULL,
  `ResponseCode` INT NOT NULL,
  `RequestSummaryID` INT(10) NULL,
  `SummaryEntryID` INT NOT NULL,
  PRIMARY KEY (`ResponseCodeDetailId`),
  INDEX `fk_ResponsesCodeDetails_RequestSummary1_idx` (`RequestSummaryID` ASC),
  INDEX `fk_ResponsesCodeDetails_SummaryData1_idx` (`SummaryEntryID` ASC),
  CONSTRAINT `fk_ResponsesCodeDetails_RequestSummary1`
    FOREIGN KEY (`RequestSummaryID`)
    REFERENCES `apc`.`RequestSummary` (`RequestSummaryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ResponsesCodeDetails_SummaryData1`
    FOREIGN KEY (`SummaryEntryID`)
    REFERENCES `apc`.`SummaryData` (`SummaryEntryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apc`.`RequestDurationDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apc`.`RequestDurationDetail` (
  `RequestDurationId` INT NOT NULL AUTO_INCREMENT,
  `SummaryEntryID` INT NOT NULL,
  `DurationDetail` VARCHAR(45) NOT NULL,
  `RequestSummaryID` INT(10) NOT NULL,
  PRIMARY KEY (`RequestDurationId`),
  INDEX `fk_RequestDuration_SummaryData1_idx` (`SummaryEntryID` ASC),
  INDEX `fk_RequestDurationDetail_RequestSummary1_idx` (`RequestSummaryID` ASC),
  CONSTRAINT `fk_RequestDuration_SummaryData1`
    FOREIGN KEY (`SummaryEntryID`)
    REFERENCES `apc`.`SummaryData` (`SummaryEntryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RequestDurationDetail_RequestSummary1`
    FOREIGN KEY (`RequestSummaryID`)
    REFERENCES `apc`.`RequestSummary` (`RequestSummaryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
