-- MySQL Script generated by MySQL Workbench
-- 03/04/15 15:56:35
-- Model: New Model    Version: 1.0
/* SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; */
/* SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; */
/* SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES'; */

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema apc
-- -----------------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA = apc ;

-- -----------------------------------------------------
-- Table `apc`.`ControllerDefinition`
-- -----------------------------------------------------
CREATE TABLE apc.ControllerDefinition (
  ControllerDefinitionID NUMBER(10) NOT NULL,
  Users NUMBER(10) NOT NULL,
  ControllerName VARCHAR2(200) NOT NULL,
  PRIMARY KEY (ControllerDefinitionID))
;


-- -----------------------------------------------------
-- Table `apc`.`ScenarioDefinition`
-- -----------------------------------------------------
CREATE TABLE apc.ScenarioDefinition (
  ScenarioDefinitionID NUMBER(10) NOT NULL,
  ScenarioName VARCHAR2(200) NOT NULL,
  ScenarioPath VARCHAR2(2000) NULL,
  PRIMARY KEY (ScenarioDefinitionID))
;


-- -----------------------------------------------------
-- Table `apc`.`ScenarioExecution`
-- -----------------------------------------------------
CREATE TABLE apc.ScenarioExecution (
  ScenarioExecutionID NUMBER(19) NOT NULL,
  ScenarioDefintionID NUMBER(10) NOT NULL,
  SummaryOnly NUMBER(3) NOT NULL,
  PRIMARY KEY (ScenarioExecutionID)
 ,
  CONSTRAINT scenario_executions
    FOREIGN KEY (ScenarioDefintionID)
    REFERENCES apc.ScenarioDefinition (ScenarioDefinitionID)
    ON DELETE CASCADE
    )
;

CREATE INDEX scenario_executions_idx ON apc.ScenarioExecution (ScenarioDefintionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`FailureDefinition`
-- -----------------------------------------------------
CREATE TABLE apc.FailureDefinition (
  FailureDefinitionID NUMBER(10) NOT NULL,
  Name VARCHAR2(2000) NOT NULL,
  PRIMARY KEY (FailureDefinitionID))
;


-- -----------------------------------------------------
-- Table `apc`.`TestcaseDefinition`
-- -----------------------------------------------------
CREATE TABLE apc.TestcaseDefinition (
  TestcaseDefinitionID NUMBER(10) NOT NULL,
  TestcaseName VARCHAR2(2000) NOT NULL,
  PRIMARY KEY (TestcaseDefinitionID))
;


-- -----------------------------------------------------
-- Table `apc`.`GoalDefinition`
-- -----------------------------------------------------
CREATE TABLE apc.GoalDefinition (
  GoalDefinitionID NUMBER(10) NOT NULL,
  GoalName CLOB NOT NULL,
  PRIMARY KEY (GoalDefinitionID))
;


-- -----------------------------------------------------
-- Table `apc`.`IterationPerExecution`
-- -----------------------------------------------------
CREATE TABLE apc.IterationPerExecution (
  IterationPerExecutionID NUMBER(10) NOT NULL,
  ScenarioExecutionID NUMBER(19) NOT NULL,
  ControllerDefinitionID NUMBER(10) NOT NULL,
  GoalDefinitionID NUMBER(10) NOT NULL,
  Name VARCHAR2(200) NOT NULL,
  Position NUMBER(10) NOT NULL,
  Duration NUMBER(10) NOT NULL,
  RampupDone NUMBER(10) NULL,
  RampdownStarted NUMBER(10) NULL,
  StartTime NUMBER(19) NULL,
  EndTime NUMBER(19) NULL,
  PRIMARY KEY (IterationPerExecutionID)
 ,
  CONSTRAINT controllers_iterations
    FOREIGN KEY (ControllerDefinitionID)
    REFERENCES apc.ControllerDefinition (ControllerDefinitionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT executions_iterations
    FOREIGN KEY (ScenarioExecutionID)
    REFERENCES apc.ScenarioExecution (ScenarioExecutionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_Iterations_Goals1
    FOREIGN KEY (GoalDefinitionID)
    REFERENCES apc.GoalDefinition (GoalDefinitionID)
    ON DELETE CASCADE
    )
;

CREATE INDEX executions_iterations_idx ON apc.IterationPerExecution (ScenarioExecutionID ASC);
CREATE INDEX controllers_iterations_idx ON apc.IterationPerExecution (ControllerDefinitionID ASC);
CREATE INDEX fk_Iterations_Goals1_idx ON apc.IterationPerExecution (GoalDefinitionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`ServerDefinition`
-- -----------------------------------------------------
CREATE TABLE apc.ServerDefinition (
  ServerDefinitionID NUMBER(10) NOT NULL,
  IP CHAR(200) NOT NULL,
  Name VARCHAR2(300) NOT NULL,
  PRIMARY KEY (ServerDefinitionID))
;


-- -----------------------------------------------------
-- Table `apc`.`LocationDefinition`
-- -----------------------------------------------------
CREATE TABLE apc.LocationDefinition (
  LocationDefinitionID NUMBER(10) NOT NULL,
  LocationName VARCHAR2(300) NULL,
  PRIMARY KEY (LocationDefinitionID))
;


-- -----------------------------------------------------
-- Table `apc`.`TestNodePerExecution`
-- -----------------------------------------------------
CREATE TABLE apc.TestNodePerExecution (
  TestNodePerExecutionID NUMBER(10) NOT NULL,
  TestNodeDefinitionID NUMBER(10) NOT NULL,
  ScenarioExecutionID NUMBER(19) NOT NULL,
  LocationDefinitionID NUMBER(10) NOT NULL,
  ErrLog CLOB NOT NULL,
  OutputLog CLOB NOT NULL,
  PRIMARY KEY (TestNodePerExecutionID)
 ,
  CONSTRAINT testnodes_testnscenario
    FOREIGN KEY (TestNodeDefinitionID)
    REFERENCES apc.ServerDefinition (ServerDefinitionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT executions_testncution
    FOREIGN KEY (ScenarioExecutionID)
    REFERENCES apc.ScenarioExecution (ScenarioExecutionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_TN_LocDefinition1
    FOREIGN KEY (LocationDefinitionID)
    REFERENCES apc.LocationDefinition (LocationDefinitionID)
    ON DELETE CASCADE
    )
;



CREATE INDEX executions_teecution_idx ON apc.TestNodePerExecution (ScenarioExecutionID ASC);
CREATE INDEX testnodes_testio_idx ON apc.TestNodePerExecution (TestNodeDefinitionID ASC);
CREATE INDEX fk_TNPE_LD1_idx ON apc.TestNodePerExecution (LocationDefinitionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`TestcaseExecution`
-- -----------------------------------------------------
CREATE TABLE apc.TestcaseExecution (
  TestcaseExecutionID NUMBER(10) NOT NULL,
  ScenarioExecutionID NUMBER(19) NOT NULL,
  TestcaseDefinitionID NUMBER(10) NOT NULL,
  IterationPerExecutionID NUMBER(10) NOT NULL,
  TestNodePerExecutionID NUMBER(10) NOT NULL,
  Offset NUMBER(10) NOT NULL,
  Duration NUMBER(10) NOT NULL,
  Success NUMBER(3) NOT NULL,
  Timestamp NUMBER(19) NOT NULL,
  Type VARCHAR2(1) NOT NULL,
  DetailedUsecaseExecution NUMBER(3) NOT NULL,
  PRIMARY KEY (TestcaseExecutionID)
 ,
  CONSTRAINT fk_txexecutions1
    FOREIGN KEY (ScenarioExecutionID)
    REFERENCES apc.ScenarioExecution (ScenarioExecutionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_Testcasfinition1
    FOREIGN KEY (TestcaseDefinitionID)
    REFERENCES apc.TestcaseDefinition (TestcaseDefinitionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_Testcecution1
    FOREIGN KEY (IterationPerExecutionID)
    REFERENCES apc.IterationPerExecution (IterationPerExecutionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_TestcaseExecution1
    FOREIGN KEY (TestNodePerExecutionID)
    REFERENCES apc.TestNodePerExecution (TestNodePerExecutionID)
    ON DELETE CASCADE
    )
;

CREATE INDEX fk_txexecutions1_idx ON apc.TestcaseExecution (ScenarioExecutionID ASC);
CREATE INDEX Timestamp_UNIQUE ON apc.TestcaseExecution (Timestamp ASC);
CREATE INDEX fk_Testcefinition1_idx ON apc.TestcaseExecution (TestcaseDefinitionID ASC);
CREATE INDEX fk_tcpe1_idx ON apc.TestcaseExecution (IterationPerExecutionID ASC);
CREATE INDEX fk_TestcarExecution1_idx ON apc.TestcaseExecution (TestNodePerExecutionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`FailingTestcaseExecution`
-- -----------------------------------------------------
CREATE TABLE apc.FailingTestcaseExecution (
  TestcaseExecutionID NUMBER(10) NOT NULL,
  FailureID NUMBER(10) NOT NULL,
  PRIMARY KEY (TestcaseExecutionID)
 ,
  CONSTRAINT tx_ftx
    FOREIGN KEY (TestcaseExecutionID)
    REFERENCES apc.TestcaseExecution (TestcaseExecutionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT failures_ftx
    FOREIGN KEY (FailureID)
    REFERENCES apc.FailureDefinition (FailureDefinitionID)
    ON DELETE CASCADE
    )
;

CREATE INDEX failures_ftidx ON apc.FailingTestcaseExecution (FailureID ASC);


-- -----------------------------------------------------
-- Table `apc`.`ServerMonitoring`
-- -----------------------------------------------------
CREATE TABLE apc.ServerMonitoring (
  ServerMonitoringID NUMBER(10) NOT NULL,
  ServerDefinitionID NUMBER(10) NOT NULL,
  IterationPerExecutionID NUMBER(10) NOT NULL,
  Type VARCHAR2(15) NOT NULL,
  PRIMARY KEY (ServerMonitoringID)
 ,
  CONSTRAINT iterations_monitoring
    FOREIGN KEY (IterationPerExecutionID)
    REFERENCES apc.IterationPerExecution (IterationPerExecutionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT nodes_monitoring
    FOREIGN KEY (ServerDefinitionID)
    REFERENCES apc.ServerDefinition (ServerDefinitionID)
    ON DELETE CASCADE
    )
;


CREATE INDEX nodes_monitoring_idx ON apc.ServerMonitoring (ServerDefinitionID ASC);
CREATE INDEX iterations_monitoring_idx ON apc.ServerMonitoring (IterationPerExecutionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`StepDefinition`
-- -----------------------------------------------------
CREATE TABLE apc.StepDefinition (
  StepDefinitionID NUMBER(10) NOT NULL,
  TestcaseDefinitionID NUMBER(10) NOT NULL,
  Name VARCHAR2(200) NOT NULL,
  PRIMARY KEY (StepDefinitionID)
 ,
  CONSTRAINT usecases_stepdefinitions
    FOREIGN KEY (TestcaseDefinitionID)
    REFERENCES apc.TestcaseDefinition (TestcaseDefinitionID)
    ON DELETE CASCADE
    )
;

CREATE INDEX usecases_idx ON apc.StepDefinition (TestcaseDefinitionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`StepPerTestcaseExecution`
-- -----------------------------------------------------
CREATE TABLE apc.StepPerTestcaseExecution (
  StepPerTestcaseExecutionID NUMBER(10) NOT NULL,
  TestcaseExecutionID NUMBER(10) NOT NULL,
  StepDefinitionID NUMBER(10) NOT NULL,
  PositionInTestcase NUMBER(5) NOT NULL,
  Duration NUMBER(10) NOT NULL,
  PRIMARY KEY (StepPerTestcaseExecutionID)
 ,
  CONSTRAINT tx_sp
    FOREIGN KEY (TestcaseExecutionID)
    REFERENCES apc.TestcaseExecution (TestcaseExecutionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT steps_sp
    FOREIGN KEY (StepDefinitionID)
    REFERENCES apc.StepDefinition (StepDefinitionID)
    ON DELETE CASCADE
    )
;

CREATE INDEX steps_sp_idx ON apc.StepPerTestcaseExecution (StepDefinitionID ASC);
CREATE INDEX tx_sp_idx ON apc.StepPerTestcaseExecution (TestcaseExecutionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`RequestDefinition`
-- -----------------------------------------------------
CREATE TABLE apc.RequestDefinition (
  RequestDefinitionID NUMBER(10) NOT NULL,
  MIME VARCHAR2(45) NOT NULL,
  RequestValue VARCHAR2(600) NOT NULL,
  PRIMARY KEY (RequestDefinitionID))
;


-- -----------------------------------------------------
-- Table `apc`.`RequestPerStep`
-- -----------------------------------------------------
CREATE TABLE apc.RequestPerStep (
  RequestPerStepID NUMBER(10) NOT NULL,
  StepPerTestcaseExecutionID NUMBER(10) NOT NULL,
  RequestDefinitionID NUMBER(10) NOT NULL,
  Duration NUMBER(10) NOT NULL,
  Response BLOB NOT NULL,
  RequestHeaders VARCHAR2(3000) NULL,
  ResponseCode NUMBER(10) NULL,
  PRIMARY KEY (RequestPerStepID)
 ,
  CONSTRAINT steps_responses
    FOREIGN KEY (StepPerTestcaseExecutionID)
    REFERENCES apc.StepPerTestcaseExecution (StepPerTestcaseExecutionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_Requests_RequestDefinition1
    FOREIGN KEY (RequestDefinitionID)
    REFERENCES apc.RequestDefinition (RequestDefinitionID)
    ON DELETE CASCADE
    )
;


CREATE INDEX steps_responses_idx ON apc.RequestPerStep (StepPerTestcaseExecutionID ASC);
CREATE INDEX fk_Requests_RD_idx ON apc.RequestPerStep (RequestDefinitionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`SummaryData`
-- -----------------------------------------------------
CREATE TABLE apc.SummaryData (
  SummaryEntryID NUMBER(10) NOT NULL,
  PercentileFound NUMBER(3) NOT NULL,
  TotalSuccess NUMBER(10) NOT NULL,
  TotalFailures NUMBER(10) NOT NULL,
  MaxDuration NUMBER(10) NULL,
  MinDuration NUMBER(10) NULL,
  AvgDuration NUMBER(10) NULL,
  DurationStdDev NUMBER(10) NULL,
  Duration85 NUMBER(10) NULL,
  Duration90 NUMBER(10) NULL,
  Duration95 NUMBER(10) NULL,
  MaxSize NUMBER(10) NULL,
  MinSize NUMBER(10) NULL,
  AvgSize NUMBER(10) NULL,
  SizeStdDev NUMBER(10) NULL,
  Size85 NUMBER(10) NULL,
  Size90 NUMBER(10) NULL,
  Size95 NUMBER(10) NULL,
  ScenarioExecutionID NUMBER(19) NOT NULL,
  PRIMARY KEY (SummaryEntryID)
 ,
  CONSTRAINT fk_Se_SE1
    FOREIGN KEY (ScenarioExecutionID)
    REFERENCES apc.ScenarioExecution (ScenarioExecutionID)
    ON DELETE CASCADE
    )
;


CREATE INDEX fk_Se_SE1_idx ON apc.SummaryData (ScenarioExecutionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`TestcaseSummary`
-- -----------------------------------------------------
CREATE TABLE apc.TestcaseSummary (
  TestcaseSummaryID NUMBER(10) NOT NULL,
  TestcaseDefinitionID NUMBER(10) NOT NULL,
  TestcasePercentage BINARY_DOUBLE NOT NULL,
  Users NUMBER(10) NOT NULL,
  SummaryEntryID NUMBER(10) NULL,
  PRIMARY KEY (TestcaseSummaryID)
 ,
  CONSTRAINT usecases_sequence
    FOREIGN KEY (TestcaseDefinitionID)
    REFERENCES apc.TestcaseDefinition (TestcaseDefinitionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_Tesion_SummaryData1
    FOREIGN KEY (SummaryEntryID)
    REFERENCES apc.SummaryData (SummaryEntryID)
    ON DELETE CASCADE
    )
;

CREATE INDEX usecases_sequence_idx ON apc.TestcaseSummary (TestcaseDefinitionID ASC);
CREATE INDEX fk_Testion_SummaryData1_idx ON apc.TestcaseSummary (SummaryEntryID ASC);


-- -----------------------------------------------------
-- Table `apc`.`FailingStep`
-- -----------------------------------------------------
CREATE TABLE apc.FailingStep (
  StepPerTestcaseExecutionID NUMBER(10) NOT NULL,
  FailureDefinitionID NUMBER(10) NOT NULL,
  PRIMARY KEY (StepPerTestcaseExecutionID)
 ,
  CONSTRAINT spt_warningsteps
    FOREIGN KEY (StepPerTestcaseExecutionID)
    REFERENCES apc.StepPerTestcaseExecution (StepPerTestcaseExecutionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_FS_FE1
    FOREIGN KEY (FailureDefinitionID)
    REFERENCES apc.FailureDefinition (FailureDefinitionID)
    ON DELETE CASCADE
    )
;

CREATE INDEX fk_FS_FE1_idx ON apc.FailingStep (FailureDefinitionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`ResourceMonitoring`
-- -----------------------------------------------------
CREATE TABLE apc.ResourceMonitoring (
  ResourceMonitoringID NUMBER(10) NOT NULL,
  EntryType VARCHAR2(200) NULL,
  TestNodeMonitoringID NUMBER(10) NOT NULL
 ,
  PRIMARY KEY (ResourceMonitoringID),
  CONSTRAINT fk_APies_Monitoring1
    FOREIGN KEY (TestNodeMonitoringID)
    REFERENCES apc.ServerMonitoring (ServerMonitoringID)
    ON DELETE CASCADE
    )
;


CREATE INDEX fk_APies_Monitoring1_idx ON apc.ResourceMonitoring (TestNodeMonitoringID ASC);


-- -----------------------------------------------------
-- Table `apc`.`MonitoringData`
-- -----------------------------------------------------
CREATE TABLE apc.MonitoringData (
  MonitoringDataID NUMBER(10) NOT NULL,
  ResourceMonitoringID NUMBER(10) NOT NULL,
  Value BINARY_DOUBLE NOT NULL,
  Offset NUMBER(10) NULL,
  PRIMARY KEY (MonitoringDataID)
 ,
  CONSTRAINT fk_APiesD_ME1
    FOREIGN KEY (ResourceMonitoringID)
    REFERENCES apc.ResourceMonitoring (ResourceMonitoringID)
    ON DELETE CASCADE
    )
;

CREATE INDEX fk_APiesD_ME1_idx ON apc.MonitoringData (ResourceMonitoringID ASC);


-- -----------------------------------------------------
-- Table `apc`.`IterationSummary`
-- -----------------------------------------------------
CREATE TABLE apc.IterationSummary (
  SummaryReportID NUMBER(10) NOT NULL,
  IterationID NUMBER(10) NOT NULL,
  SummaryType VARCHAR2(45) NULL,
  PRIMARY KEY (SummaryReportID)
 ,
  CONSTRAINT fk_SR_Iterations1
    FOREIGN KEY (IterationID)
    REFERENCES apc.IterationPerExecution (IterationPerExecutionID)
    ON DELETE CASCADE
    )
;


CREATE INDEX fk_SR_Iterations1_idx ON apc.IterationSummary (IterationID ASC);


-- -----------------------------------------------------
-- Table `apc`.`IterationSummaryData`
-- -----------------------------------------------------
CREATE TABLE apc.IterationSummaryData (
  IterationSummaryEntriesId NUMBER(10) NOT NULL,
  SummaryReportID NUMBER(10) NOT NULL,
  Offset NUMBER(10) NULL,
  Value BINARY_DOUBLE NULL,
  PRIMARY KEY (IterationSummaryEntriesId)
 ,
  CONSTRAINT fk_ISE_IterationSummary1
    FOREIGN KEY (SummaryReportID)
    REFERENCES apc.IterationSummary (SummaryReportID)
    ON DELETE CASCADE
    )
;


CREATE INDEX fk_ISE_IterationSummary1_idx ON apc.IterationSummaryData (SummaryReportID ASC);


-- -----------------------------------------------------
-- Table `apc`.`StepSummary`
-- -----------------------------------------------------
CREATE TABLE apc.StepSummary (
  StepSummaryID NUMBER(10) NOT NULL,
  StepDefinitionID NUMBER(10) NOT NULL,
  TestcaseSummaryID NUMBER(10) NOT NULL,
  SummaryEntryID NUMBER(10) NOT NULL,
  PRIMARY KEY (StepSummaryID)
 ,
  CONSTRAINT fk_TS_SummaryEntries10
    FOREIGN KEY (SummaryEntryID)
    REFERENCES apc.SummaryData (SummaryEntryID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_StepsSummary_SD_1
    FOREIGN KEY (StepDefinitionID)
    REFERENCES apc.StepDefinition (StepDefinitionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_SS_TS1
    FOREIGN KEY (TestcaseSummaryID)
    REFERENCES apc.TestcaseSummary (TestcaseSummaryID)
    ON DELETE CASCADE
    )
;


CREATE INDEX fk_TS_SummaryEntries1_idx ON apc.StepSummary (SummaryEntryID ASC);
CREATE INDEX fk_StepsSummary_SD_1_idx ON apc.StepSummary (StepDefinitionID ASC);
CREATE INDEX fk_SS_TS1_idx ON apc.StepSummary (TestcaseSummaryID ASC);


-- -----------------------------------------------------
-- Table `apc`.`RequestSummary`
-- -----------------------------------------------------
CREATE TABLE apc.RequestSummary (
  RequestSummaryID NUMBER(10) NOT NULL,
  RequestDefinitionID NUMBER(10) NOT NULL,
  StepSummaryID NUMBER(10) NULL,
  IterationPerExecutionID NUMBER(10) NULL,
  SummaryEntryID NUMBER(10) NOT NULL,
  PRIMARY KEY (RequestSummaryID)
 ,
  CONSTRAINT fk_TS_SummaryEntries100
    FOREIGN KEY (SummaryEntryID)
    REFERENCES apc.SummaryData (SummaryEntryID)
    ON DELETE CASCADE
   ,
  CONSTRAINT fk_RS_RequestDefinition1
    FOREIGN KEY (RequestDefinitionID)
    REFERENCES apc.RequestDefinition (RequestDefinitionID)
    ON DELETE CASCADE
   ,
  CONSTRAINT fk_RS_StepsSummary1
    FOREIGN KEY (StepSummaryID)
    REFERENCES apc.StepSummary (StepSummaryID)
    ON DELETE CASCADE
   ,
  CONSTRAINT fk_RS_IPE1
    FOREIGN KEY (IterationPerExecutionID)
    REFERENCES apc.IterationPerExecution (IterationPerExecutionID)
    ON DELETE CASCADE
   )
;

CREATE INDEX fk_TS_SummaryEntries1_id_x ON apc.RequestSummary (SummaryEntryID ASC);
CREATE INDEX fk_RS_RD_idx ON apc.RequestSummary (RequestDefinitionID ASC);
CREATE INDEX fk_RS_StepsSummary1_idx ON apc.RequestSummary (StepSummaryID ASC);
CREATE INDEX fk_RS_IPE1_idx ON apc.RequestSummary (IterationPerExecutionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`TestcaseExecutionLog`
-- -----------------------------------------------------
CREATE TABLE apc.TestcaseExecutionLog (
  TestcaseExecutionID NUMBER(10) NOT NULL,
  OuptutLog CLOB NOT NULL,
  ErrorLog CLOB NOT NULL,
  PRIMARY KEY (TestcaseExecutionID),
  CONSTRAINT fk_TL_Transactions1
    FOREIGN KEY (TestcaseExecutionID)
    REFERENCES apc.TestcaseExecution (TestcaseExecutionID)
    ON DELETE CASCADE
    )
;


-- -----------------------------------------------------
-- Table `apc`.`PercentileCache`
-- -----------------------------------------------------
CREATE TABLE apc.PercentileCache (
  PercentileCacheID NUMBER(10) NOT NULL,
  ResourceId NUMBER(10) NOT NULL,
  Value NUMBER(10) NOT NULL,
  LocationDefinitionID NUMBER(10) NOT NULL,
  TestNodePerExecutionID NUMBER(10) NOT NULL);


-- -----------------------------------------------------
-- Table `apc`.`RequestFailureSummary`
-- -----------------------------------------------------
CREATE TABLE apc.RequestFailureSummary (
  RequestFailureSummaryID NUMBER(10) NOT NULL,
  RequestSummaryID NUMBER(10) NOT NULL,
  FailureDefinitionID NUMBER(10) NOT NULL,
  Total NUMBER(10) NOT NULL,
  PRIMARY KEY (RequestFailureSummaryID)
 ,
  CONSTRAINT fk_RS_RequestSummary1
    FOREIGN KEY (RequestSummaryID)
    REFERENCES apc.RequestSummary (RequestSummaryID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_RS_FE1
    FOREIGN KEY (FailureDefinitionID)
    REFERENCES apc.FailureDefinition (FailureDefinitionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_RS_SummaryData
    FOREIGN KEY (Total)
    REFERENCES apc.SummaryData (SummaryEntryID)
    ON DELETE CASCADE
    )
;


CREATE INDEX fk_RS_RequestSummary1_idx ON apc.RequestFailureSummary (RequestSummaryID ASC);
CREATE INDEX fk_RS_FE1_idx ON apc.RequestFailureSummary (FailureDefinitionID ASC);
CREATE INDEX fk_RS_Se_idx ON apc.RequestFailureSummary (Total ASC);


-- -----------------------------------------------------
-- Table `apc`.`StepFailureSummary`
-- -----------------------------------------------------
CREATE TABLE apc.StepFailureSummary (
  StepFailureSummaryID NUMBER(10) NOT NULL,
  StepSummaryID NUMBER(10) NOT NULL,
  FailureDefinitionID NUMBER(10) NOT NULL,
  Total NUMBER(10) NOT NULL,
  PRIMARY KEY (StepFailureSummaryID)
 ,
  CONSTRAINT fk_SFS_StepSummary1
    FOREIGN KEY (StepSummaryID)
    REFERENCES apc.StepSummary (StepSummaryID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_SFS_FE1
    FOREIGN KEY (FailureDefinitionID)
    REFERENCES apc.FailureDefinition (FailureDefinitionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_TFS_SummaryData
    FOREIGN KEY (Total)
    REFERENCES apc.SummaryData (SummaryEntryID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_StepFailureSummary
    FOREIGN KEY (Total)
    REFERENCES apc.SummaryData (SummaryEntryID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_RequestFailureSummary
    FOREIGN KEY (Total)
    REFERENCES apc.SummaryData (SummaryEntryID)
    ON DELETE CASCADE
    )
;


CREATE INDEX fk_SFS_StepSummary1_idx ON apc.StepFailureSummary (StepSummaryID ASC);
CREATE INDEX fk_SFS_FE1_idx ON apc.StepFailureSummary (FailureDefinitionID ASC);
CREATE INDEX fk_SFS_Se_idx ON apc.StepFailureSummary (Total ASC);


-- -----------------------------------------------------
-- Table `apc`.`TestcaseFailureSummary`
-- -----------------------------------------------------
CREATE TABLE apc.TestcaseFailureSummary (
  TestcaseFailureSummaryID NUMBER(10) NOT NULL,
  TestcasePerIterationID NUMBER(10) NOT NULL,
  FailureDefinitionID NUMBER(10) NOT NULL,
  Total NUMBER(10) NOT NULL,
  PRIMARY KEY (TestcaseFailureSummaryID)
 ,
  CONSTRAINT fk_TFS_TPIS1
    FOREIGN KEY (TestcasePerIterationID)
    REFERENCES apc.TestcaseSummary (TestcaseSummaryID)
   ,
  CONSTRAINT fk_TFS_FE1
    FOREIGN KEY (FailureDefinitionID)
    REFERENCES apc.FailureDefinition (FailureDefinitionID)
   ,
  CONSTRAINT fk_TFS_SummaryData1
    FOREIGN KEY (Total)
    REFERENCES apc.SummaryData (SummaryEntryID)
   )
;


CREATE INDEX fk_TFS_TPIS_idx ON apc.TestcaseFailureSummary (TestcasePerIterationID ASC);
CREATE INDEX fk_TFS_FE1_idx ON apc.TestcaseFailureSummary (FailureDefinitionID ASC);
CREATE INDEX fk_TFS_SummaryData1_idx ON apc.TestcaseFailureSummary (Total ASC);


-- -----------------------------------------------------
-- Table `apc`.`FailingRequest`
-- -----------------------------------------------------
CREATE TABLE apc.FailingRequest (
  RequestPerStepID NUMBER(10) NOT NULL,
  FailureDefinitionID NUMBER(10) NOT NULL
 ,
  PRIMARY KEY (RequestPerStepID),
  CONSTRAINT fk_FS_FE10
    FOREIGN KEY (FailureDefinitionID)
    REFERENCES apc.FailureDefinition (FailureDefinitionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_FR_RequestPerStep1
    FOREIGN KEY (RequestPerStepID)
    REFERENCES apc.RequestPerStep (RequestPerStepID)
    ON DELETE CASCADE
    )
;

CREATE INDEX fk_FS_FE91_1idx ON apc.FailingRequest (FailureDefinitionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`LocationPerIterationSummary`
-- -----------------------------------------------------
CREATE TABLE apc.LocationPerIterationSummary (
  LocationPerIterationSummaryID NUMBER(10) NOT NULL,
  LocationDefinitionID NUMBER(10) NOT NULL,
  IterationPerExecutionID NUMBER(10) NOT NULL,
  TestcasePerIterationID NUMBER(10) NOT NULL
 ,
  PRIMARY KEY (LocationPerIterationSummaryID),
  CONSTRAINT fk_LPIS_LD1
    FOREIGN KEY (LocationDefinitionID)
    REFERENCES apc.LocationDefinition (LocationDefinitionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_LPIS_IPE1
    FOREIGN KEY (IterationPerExecutionID)
    REFERENCES apc.IterationPerExecution (IterationPerExecutionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_LPIS_TPIS1
    FOREIGN KEY (TestcasePerIterationID)
    REFERENCES apc.TestcaseSummary (TestcaseSummaryID)
    ON DELETE CASCADE
    )
;

CREATE INDEX fk_LPIS_LD1_idx ON apc.LocationPerIterationSummary (LocationDefinitionID ASC);
CREATE INDEX fk_LPIS_IPE1_idx ON apc.LocationPerIterationSummary (IterationPerExecutionID ASC);
CREATE INDEX fk_LPIS_TPIS_idx ON apc.LocationPerIterationSummary (TestcasePerIterationID ASC);


-- -----------------------------------------------------
-- Table `apc`.`TestNodePerIterationSummary`
-- -----------------------------------------------------
CREATE TABLE apc.TestNodePerIterationSummary (
  TestNodePerIterationSummaryID NUMBER(10) CHECK (TestNodePerIterationSummaryID > 0) NOT NULL,
  TestNodePerExecutionID NUMBER(10) NOT NULL,
  TestcasePerIterationID NUMBER(10) NOT NULL,
  IterationPerExecutionID NUMBER(10) NOT NULL
 ,
  PRIMARY KEY (TestNodePerIterationSummaryID)
 ,
  CONSTRAINT fk_TNPIS_TNPI
    FOREIGN KEY (TestNodePerExecutionID)
    REFERENCES apc.TestNodePerExecution (TestNodePerExecutionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_TNPIS_TPIS1
    FOREIGN KEY (TestcasePerIterationID)
    REFERENCES apc.TestcaseSummary (TestcaseSummaryID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_TNPIS_IPE1
    FOREIGN KEY (IterationPerExecutionID)
    REFERENCES apc.IterationPerExecution (IterationPerExecutionID)
    ON DELETE CASCADE
    )
;

CREATE INDEX fk_TNPIS_TNPE_idx ON apc.TestNodePerIterationSummary (TestNodePerExecutionID ASC);
CREATE INDEX fk_TNPIS_TPIS_idx ON apc.TestNodePerIterationSummary (TestcasePerIterationID ASC);
CREATE INDEX fk_TNPIS_IPE1_idx ON apc.TestNodePerIterationSummary (IterationPerExecutionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`TestcasePerIterationSummary`
-- -----------------------------------------------------
CREATE TABLE apc.TestcasePerIterationSummary (
  TestcasePerIterationSummaryID NUMBER(10) NOT NULL,
  IterationPerExecutionID NUMBER(10) NOT NULL,
  TestcaseSummaryID NUMBER(10) NOT NULL,
  PRIMARY KEY (TestcasePerIterationSummaryID)
 ,
  CONSTRAINT fk_TPIS_IPE1
    FOREIGN KEY (IterationPerExecutionID)
    REFERENCES apc.IterationPerExecution (IterationPerExecutionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_TPIS_TS1
    FOREIGN KEY (TestcaseSummaryID)
    REFERENCES apc.TestcaseSummary (TestcaseSummaryID)
    ON DELETE CASCADE
    )
;

CREATE INDEX fk_TPIS_IPE1_idx ON apc.TestcasePerIterationSummary (IterationPerExecutionID ASC);
CREATE INDEX fk_TPIS_TS1_idx ON apc.TestcasePerIterationSummary (TestcaseSummaryID ASC);


-- -----------------------------------------------------
-- Table `apc`.`NodePerIterationSummary`
-- -----------------------------------------------------
CREATE TABLE apc.NodePerIterationSummary (
  NodePerIterationSummaryID NUMBER(10) NOT NULL,
  IterationPerExecutionID NUMBER(10) NOT NULL,
  TestcasePerIterationID NUMBER(10) NOT NULL,
  TestNodePerExecutionID NUMBER(10) NOT NULL
 ,
  PRIMARY KEY (NodePerIterationSummaryID)
 ,
  CONSTRAINT fk_LPIS_IPE10
    FOREIGN KEY (IterationPerExecutionID)
    REFERENCES apc.IterationPerExecution (IterationPerExecutionID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_LPIS_TPIS10
    FOREIGN KEY (TestcasePerIterationID)
    REFERENCES apc.TestcaseSummary (TestcaseSummaryID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_NPIS_TestNodePerExecution1
    FOREIGN KEY (TestNodePerExecutionID)
    REFERENCES apc.TestNodePerExecution (TestNodePerExecutionID)
    ON DELETE CASCADE
    )
;

CREATE INDEX fk_LPIS_IPE12_idx ON apc.NodePerIterationSummary (IterationPerExecutionID ASC);
CREATE INDEX fk_LPIS_TPIS12_idx ON apc.NodePerIterationSummary (TestcasePerIterationID ASC);
CREATE INDEX fk_NPIS_TNPEI_idx ON apc.NodePerIterationSummary (TestNodePerExecutionID ASC);


-- -----------------------------------------------------
-- Table `apc`.`ResponseCodeDetail`
-- -----------------------------------------------------
CREATE TABLE apc.ResponseCodeDetail (
  ResponseCodeDetailId NUMBER(10) NOT NULL,
  ResponseCode NUMBER(10) NOT NULL,
  RequestSummaryID NUMBER(10) NULL,
  SummaryEntryID NUMBER(10) NOT NULL,
  PRIMARY KEY (ResponseCodeDetailId)
 ,
  CONSTRAINT fk_RCD_RequestSummary1
    FOREIGN KEY (RequestSummaryID)
    REFERENCES apc.RequestSummary (RequestSummaryID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_RCD_SummaryData1
    FOREIGN KEY (SummaryEntryID)
    REFERENCES apc.SummaryData (SummaryEntryID)
    ON DELETE CASCADE
    )
;

CREATE INDEX fk_RCD_RequestSummary1_idx ON apc.ResponseCodeDetail (RequestSummaryID ASC);
CREATE INDEX fk_RCD_SummaryData1_idx ON apc.ResponseCodeDetail (SummaryEntryID ASC);


-- -----------------------------------------------------
-- Table `apc`.`RequestDurationDetail`
-- -----------------------------------------------------
CREATE TABLE apc.RequestDurationDetail (
  RequestDurationId NUMBER(10) NOT NULL,
  SummaryEntryID NUMBER(10) NOT NULL,
  DurationDetail VARCHAR2(45) NOT NULL,
  RequestSummaryID NUMBER(10) NOT NULL,
  PRIMARY KEY (RequestDurationId)
 ,
  CONSTRAINT fk_RS_SummaryData1
    FOREIGN KEY (SummaryEntryID)
    REFERENCES apc.SummaryData (SummaryEntryID)
    ON DELETE CASCADE
    ,
  CONSTRAINT fk_RDD_RequestSummary1
    FOREIGN KEY (RequestSummaryID)
    REFERENCES apc.RequestSummary (RequestSummaryID)
    ON DELETE CASCADE
    )
;


CREATE INDEX fk_RS_SummaryData1_idx ON apc.RequestDurationDetail (SummaryEntryID ASC);
CREATE INDEX fk_RDD_RSD_idx ON apc.RequestDurationDetail (RequestSummaryID ASC);


/* SET SQL_MODE=@OLD_SQL_MODE; */
/* SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; */
/* SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */


CREATE SEQUENCE hibernate_sequence
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;